### ISSUE TITLE
Test set trop lourd pour Github

### ISSUE THREAD

**Issue by Benoit-Muller** [CS-433/ml-project-1-alemporter#2]
La taille maximum d'un fichier sur Github est de **25Mo**. Le le test set `test.csv` fait **109,3Mo**, et quand même **40,1 Mo** en _zip_.

 On a pas besoin que les data sets soient dans le Github avec le code? Je veux dire que quand on va travailler sur notre version locale, reliée à Github, il faudra bien pouvoir load le data depuis le repository dans lequel on sera non? Si dans notre code commun on appelle un fichier extérieur au repository, qui est dans notre ordi perso, le non de chemin sera pas le même pour chacun de nous... Des idées?

Source des fichiers dans le challenge AIcrowd: [https://www.aicrowd.com/challenges/epfl-machine-learning-higgs/dataset_files](url)

**Comment by osflo** [comment]
Oui il faut l'avoir en local et mettre le chemin dans le code, pour la version finale il faut mettre dans le read me où doit aller le data file exactement (la question a été posé sur le forum)
